pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "CloudTermPro"
include ':app'
include ':core-ssh'
include ':vault'
include ':sync-providers'
include ':cloud-sync'
include ':terminal'
include ':ui-shared'